#!/usr/bin/env node
/**
 * Generate data/visibility.md — the checkbox list that decides which robots the
 * gallery shows.
 *
 * The rows are derived from data/robots.json (name, maker, upstream link), the
 * checkboxes are hand-edited, and re-running this script keeps them: it rewrites
 * every row but carries each id's current state across. New entries in the
 * registry arrive checked, which matches how the site treats an id it cannot
 * find in the file.
 *
 *   node scripts/build_visibility.mjs            # write data/visibility.md
 *   node scripts/build_visibility.mjs --check    # fail if it is out of date
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { parseVisibility } from '../web/js/registry.js';

const root = new URL('..', import.meta.url);
const registry = JSON.parse(readFileSync(new URL('data/robots.json', root)));
const out = new URL('data/visibility.md', root);
const check = process.argv.includes('--check');

const previous = existsSync(out) ? parseVisibility(readFileSync(out, 'utf8')) : new Map();

const HEADER = `# 展示开关 · Gallery visibility

<!--
  由 \`npm run visibility\` 从 data/robots.json 生成。
  Generated by \`npm run visibility\` from data/robots.json.
  方括号以外的内容会在下次生成时被覆盖 — everything but the checkboxes is rewritten.
-->

网站在启动时读取本文件：**勾选 \`[x]\` 的条目显示在合集里，清空成 \`[ ]\` 的条目不显示。**
改完直接提交，不需要重新构建注册表，也不用改 \`data/robots.json\`。

- 反引号里的 \`id\` 是网站用来匹配的唯一标识，请不要改动；后面的名称、组织和上游链接只是给人看的。
- 被隐藏的条目不会出现在网格、分类计数、搜索结果和详情页的上一个/下一个里；
  直接访问 \`#robot=<id>\` 也会跳回合集首页。
- 本文件缺失或读取失败时网站显示全部条目；已在注册表里、但还没写进本文件的机器人同样默认显示。
- 注册表变动后跑 \`npm run visibility\` 刷新列表，现有的勾选状态会被保留。

The gallery fetches this file at startup: rows checked \`[x]\` are shown, rows left
\`[ ]\` are hidden. Edit, commit, done — no rebuild. The \`id\` in backticks is what
the site matches on; the name, organisation and upstream link after it are for
human readers.
`;

/** One task-list row: checkbox, id, name, organisation, upstream link. */
function row(robot) {
  const shown = previous.get(robot.id) !== false;
  const maker = robot.maker || '—';
  const { github, description, tree_url: treeUrl, repo_url: repoUrl, mirror } = robot.source;
  // A mirrored entry has no repository to name, so the row points at the
  // archive it is read from instead — and says that is what it is.
  const label = mirror
    ? `${mirror.host} (mirror)`
    : [github, description].filter(Boolean).join(' · ') || robot.id;
  const url = treeUrl || repoUrl || mirror?.site;
  const link = url ? `[${label}](${url})` : label;
  return `- [${shown ? 'x' : ' '}] \`${robot.id}\` **${robot.name}** — ${maker} — ${link}`;
}

const sections = [];
const seen = new Set();
for (const category of registry.categories) {
  const robots = registry.robots.filter((r) => r.category === category.id);
  if (!robots.length) continue;
  for (const robot of robots) seen.add(robot.id);
  const title = [category.label_zh, category.label].filter(Boolean).join(' ');
  sections.push(`## ${title} · ${robots.length}\n\n${robots.map(row).join('\n')}`);
}
const orphans = registry.robots.filter((r) => !seen.has(r.id));
if (orphans.length) {
  // A category the registry never declared: still listable, still switchable.
  sections.push(`## 其他 Uncategorised · ${orphans.length}\n\n${orphans.map(row).join('\n')}`);
}

const text = `${HEADER}\n${sections.join('\n\n')}\n`;
const current = existsSync(out) ? readFileSync(out, 'utf8') : null;

if (check) {
  if (current === text) {
    console.log(`data/visibility.md is up to date (${registry.robots.length} entries)`);
  } else {
    console.error('data/visibility.md is out of date — run `npm run visibility`');
    process.exitCode = 1;
  }
} else if (current === text) {
  console.log(`data/visibility.md unchanged (${registry.robots.length} entries)`);
} else {
  writeFileSync(out, text);
  const hidden = registry.robots.filter((r) => previous.get(r.id) === false).length;
  console.log(
    `wrote data/visibility.md — ${registry.robots.length} entries, ` +
      `${registry.robots.length - hidden} shown, ${hidden} hidden`,
  );
}
